### ISSUE TITLE
connect through proxy

### ISSUE THREAD

**Issue by peterWab** [lesnuages/hershell#2]
hi,
how can i make hershell connect through private proxy please

**Comment by lesnuages** [comment]
Long story short: you can't.

You would have to implement another transport protocol that is proxy aware. Hershell just makes a reverse TLS connection, it does not use any application layer protocol. One way to do that would be to change the code for the agent to communicate other HTTPS, implement a custom server side handler, and make it proxy aware.

Another way would be to tunnel Hershell's traffic inside another tool that would be proxy aware.
